-- Run after schema.sql. Safe to run again; existing product edits are preserved.
begin;
alter table public.products add column if not exists brand text;
alter table public.products add column if not exists source_url text;
insert into public.products (id,brand,name,category,description,price,size,image,tag,position,active,source_url) values
('niacinamide','The Ordinary','Niacinamide 10% + Zinc 1%','Skincare','A lightweight water-based serum with niacinamide and zinc for smoother-looking, more balanced skin.',600,'30 mL','/products/niacinamide.png','BALANCE & CARE',4,true,'https://theordinary.com/en-us/niacinamide-10-zinc-1-serum-100436.html'),
('hyaluronic','The Ordinary','Hyaluronic Acid 2% + B5 (with Ceramides)','Skincare','Daily hydration with hyaluronic acid, vitamin B5 and ceramides in a lightweight serum.',990,'30 mL','/products/hyaluronic.png','DAILY HYDRATION',5,true,'https://theordinary.com/en-us/hyaluronic-acid-2-b5-serum-with-ceramides-100637.html'),
('natural','The Ordinary','Natural Moisturizing Factors + HA','Skincare','An everyday cream with amino acids and hyaluronic acid to help keep skin comfortably hydrated.',670,'30 mL','/products/natural.png','EVERYDAY MOISTURE',6,true,'https://theordinary.com/en-us/natural-moisturizing-factors-ha-moisturizer-100435.html'),
('soft-pinch-liquid-blush','Rare Beauty','Soft Pinch Liquid Blush','Makeup','A blendable liquid blush in a soft nude mauve, with a fresh dewy finish.',2500,'Hope','/products/soft-pinch-liquid-blush.jpg','A TOUCH OF BLUSH',7,true,'https://www.rarebeauty.com/products/soft-pinch-liquid-blush?variant=43734829695111'),
('soft-pinch-tinted-lip-oil','Rare Beauty','Soft Pinch Tinted Lip Oil','Makeup','A glossy lip jelly that transforms into a lightweight oil, leaving a soft wash of nude mauve.',2400,'3 mL · Hope','/products/soft-pinch-tinted-lip-oil.jpg','SHEER COLOUR',8,true,'https://www.rarebeauty.com/products/soft-pinch-tinted-lip-oil?variant=43734835069063'),
('positive-light-liquid-luminizer-1','Rare Beauty','Positive Light Liquid Luminizer','Makeup','A liquid highlighter in cool champagne for a soft, buildable glow.',2800,'15 mL · Enlighten','/products/positive-light-liquid-luminizer-1.jpg','YOUR DAILY GLOW',9,true,'https://www.rarebeauty.com/products/positive-light-liquid-luminizer-1?variant=43734829203591'),
('cerave-hydrating-cleanser','CeraVe','Hydrating Facial Cleanser','Skincare','A gentle cream cleanser with ceramides and hyaluronic acid that removes impurities without leaving normal-to-dry skin feeling tight.',1599,'355 mL / 12 fl oz','/products/cerave-hydrating-cleanser.jpg','THE GENTLE CLEANSE',10,true,'https://www.cerave.com/skincare/cleansers/hydrating-facial-cleanser'),
('cerave-am-spf50','CeraVe','AM Facial Moisturizing Lotion SPF 50','Skincare','A lightweight daytime moisturizer with ceramides, niacinamide, hyaluronic acid and broad-spectrum SPF 50 protection.',1999,'75 mL / 2.5 fl oz','/products/cerave-am-spf50.jpg','MORNING PROTECTION',11,true,'https://www.cerave.com/skincare/moisturizers/facial-moisturizers/am-facial-moisturizing-lotion-spf-50'),
('elf-halo-glow','e.l.f. Cosmetics','Halo Glow Liquid Filter','Makeup','A multi-use complexion booster with a luminous, soft-focus finish that can be worn alone, mixed, layered or highlighted.',1500,'31.5 mL / 1.06 fl oz','/products/elf-halo-glow.png','SOFT-FOCUS GLOW',12,true,'https://www.elfcosmetics.com/products/halo-glow-liquid-filter'),
('elf-lash-n-roll','e.l.f. Cosmetics','Lash ''N Roll Mascara','Makeup','A lifting mascara with a curved, double-sided silicone brush for separated lashes and lasting curl.',700,'7 g / 0.24 oz · Black','/products/elf-lash-n-roll.png','LIFT & SEPARATE',13,true,'https://www.elfcosmetics.com/products/lash-n-roll-mascara?Color=Black'),
('fenty-gloss-bomb','Fenty Beauty','Gloss Bomb Universal Lip Luminizer','Makeup','A non-sticky, conditioning lip gloss with high-impact shine in the universally flattering Fenty Glow shade.',2300,'9 mL · Fenty Glow','/products/fenty-gloss-bomb.jpg','THE GLOSS ICON',14,true,'https://fentybeauty.com/products/gloss-bomb-universal-lip-luminizer-wattab'),
('fenty-eaze-drop','Fenty Beauty','Eaze Drop Blurring Skin Tint','Makeup','A lightweight, buildable skin tint that smooths and softly blurs while keeping the finish comfortable and natural.',4100,'32 mL / 1.08 fl oz','/products/fenty-eaze-drop.jpg','YOUR SKIN, BLURRED',15,true,'https://fentybeauty.com/products/eaze-drop-lightweight-blurring-skin-tint-20')
on conflict (id) do nothing;
commit;
