import {useState} from 'react';
import {KeyboardAvoidingView,Platform,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import {router} from 'expo-router';
import {money,useStore} from '../lib/store';

const fields=[['name','Full name'],['phone','Phone number'],['address','Street address'],['city','City'],['postal','Postal code'],['country','Country']] as const;

export default function Checkout(){
 const store=useStore();
 const [values,setValues]=useState({email:store.email||'',name:'',phone:'',address:'',city:'',postal:'',country:''}),[order,setOrder]=useState<{id:string;total:number;email_sent:boolean}|null>(null);
 const total=store.items.reduce((n,item)=>n+(store.products.find(p=>p.id===item.product_id)?.price||0)*item.quantity,0);
 async function place(){if(Object.values(values).some(v=>!v.trim())){store.setNotice('Please complete every checkout field.');return}try{setOrder(await store.checkout(values))}catch{}}
 return <SafeAreaView style={styles.safe}><KeyboardAvoidingView style={styles.flex} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView contentContainerStyle={styles.page} keyboardShouldPersistTaps="handled"><Pressable onPress={()=>router.back()}><Text style={styles.back}>‹ Back to your bag</Text></Pressable>{order?<View style={styles.success}><Text style={styles.check}>✓</Text><Text style={styles.title}>Your order is confirmed.</Text><Text style={styles.copy}>Order {order.id.slice(0,8).toUpperCase()}</Text><Text style={styles.copy}>{order.email_sent?'Your confirmation is on its way.':'Your order is saved. Email confirmation is pending.'}</Text><Text style={styles.total}>Pay {money(order.total/100)} on delivery.</Text><Pressable style={styles.button} onPress={()=>router.replace('/')}><Text style={styles.buttonText}>Back to the shop</Text></Pressable></View>:<><Text style={styles.kicker}>THE LAST LITTLE STEP</Text><Text style={styles.title}>Make it yours.</Text><TextInput style={styles.input} placeholder="Email address" keyboardType="email-address" autoCapitalize="none" value={values.email} onChangeText={email=>setValues(v=>({...v,email}))}/>{fields.map(([key,label])=><TextInput key={key} style={[styles.input,key==='address'&&styles.tall]} placeholder={label} value={values[key]} onChangeText={value=>setValues(v=>({...v,[key]:value}))}/>) }<View style={styles.payment}><Text style={styles.radio}>●</Text><View><Text style={styles.payTitle}>Pay on delivery</Text><Text style={styles.copy}>No payment is collected online.</Text></View></View><View style={styles.summary}><Text>Order total</Text><Text style={styles.total}>{money(total+(total>=60?0:6))}</Text></View><Pressable disabled={store.busy||!store.items.length} style={styles.button} onPress={place}><Text style={styles.buttonText}>{store.busy?'Placing your order…':'Place order'}</Text></Pressable></>}</ScrollView></KeyboardAvoidingView></SafeAreaView>
}

const wine='#572436',paper='#fbf9f6',line='#dfd8d6',muted='#78656c';
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:paper},flex:{flex:1},page:{padding:25,paddingBottom:60},back:{fontSize:13,color:muted,marginBottom:35},kicker:{fontSize:10,letterSpacing:1.8,fontWeight:'700',color:wine},title:{fontFamily:Platform.select({ios:'Georgia',android:'serif'}),fontSize:42,lineHeight:48,color:wine,marginVertical:14},input:{height:51,borderWidth:1,borderColor:line,backgroundColor:'white',paddingHorizontal:14,marginTop:13},tall:{height:64},payment:{backgroundColor:'#f0e5e3',borderWidth:1,borderColor:wine,padding:18,marginTop:20,flexDirection:'row',alignItems:'center',gap:14},radio:{color:wine,fontSize:20},payTitle:{fontWeight:'600'},copy:{color:muted,lineHeight:20,marginTop:5},summary:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:25},total:{fontFamily:Platform.select({ios:'Georgia',android:'serif'}),fontSize:24,color:wine},button:{height:52,backgroundColor:wine,alignItems:'center',justifyContent:'center',marginTop:22},buttonText:{color:'white',fontWeight:'600'},success:{backgroundColor:'#f0e5e3',padding:30,alignItems:'center',marginTop:35},check:{fontSize:36,color:wine}});
