import {cookies} from 'next/headers';

type Identity={id:string;email?:string};
type ConfirmationOrder={id:string;email:string;customer_name:string;items:{name:string;quantity:number}[];total:number};
type CartContext={sid:string;user:Identity|null};

export function config(){
 return {url:process.env.SUPABASE_URL,secret:process.env.SUPABASE_SECRET_KEY||process.env.SUPABASE_SERVICE_ROLE_KEY,publishable:process.env.SUPABASE_PUBLISHABLE_KEY||process.env.SUPABASE_ANON_KEY,origin:process.env.SITE_URL,mailKey:process.env.MAILGUN_API_KEY,domain:process.env.MAILGUN_DOMAIN,from:process.env.MAILGUN_FROM,region:process.env.MAILGUN_REGION};
}
export function configured(){const c=config();return !!(c.url&&c.secret&&c.publishable)}
export async function db<T=unknown>(path:string,method='GET',body?:unknown):Promise<T>{const c=config();if(!configured())throw Error('The shop is not open yet. Please check back soon.');const r=await fetch(`${c.url}/rest/v1/${path}`,{method,headers:{apikey:c.secret!,'Content-Type':'application/json',Prefer:'return=representation'},body:body===undefined?undefined:JSON.stringify(body)});if(!r.ok){console.error('Database request failed',r.status);throw Error('We could not save your changes. Please try again.')}return (r.status===204?null:await r.json()) as T}
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
export async function setCartSession(id:string){(await cookies()).set('luma_cart',id,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',path:'/',maxAge:60*60*24*30})}
export async function session(req?:Request){const jar=await cookies();const supplied=req?.headers.get('x-cart-session');let id=supplied&&uuid.test(supplied)?supplied:jar.get('luma_cart')?.value;if(!id||!uuid.test(id))id=crypto.randomUUID();if(!supplied)await setCartSession(id);return id}
export async function identity(req?:Request):Promise<Identity|null>{const authorization=req?.headers.get('authorization');const bearer=authorization?.match(/^Bearer\s+(.+)$/i)?.[1];const token=bearer||(await cookies()).get('luma_access')?.value;if(!token)return null;const c=config();const r=await fetch(`${c.url}/auth/v1/user`,{headers:{apikey:c.publishable!,Authorization:`Bearer ${token}`}});return r.ok?await r.json() as Identity:null}
export async function claimCart(sid:string,userId:string){return db<string>('rpc/claim_shared_cart','POST',{p_session:sid,p_user:userId})}
export async function cartContext(req?:Request):Promise<CartContext>{const user=await identity(req);let sid=await session(req);if(user){sid=await claimCart(sid,user.id);if(!req?.headers.get('x-cart-session'))await setCartSession(sid)}return {sid,user}}
export function sameOrigin(req:Request){const origin=req.headers.get('origin');return origin===new URL(req.url).origin||(!origin&&req.headers.get('x-luma-client')==='mobile')}
export function failure(e:unknown,status=503){return Response.json({error:e instanceof Error?e.message:'Something went wrong. Please try again.'},{status})}
export async function sendConfirmation(order:ConfirmationOrder){const c=config();if(!c.mailKey||!c.domain||!c.from)return false;const claim=await db<unknown[]>(`orders?id=eq.${order.id}&email_status=eq.pending`,'PATCH',{email_status:'sending'});if(!claim?.length)return false;const form=new FormData();form.set('from',c.from);form.set('to',order.email);form.set('subject',`Your LUMA order ${order.id.slice(0,8).toUpperCase()}`);form.set('text',`Thank you for your order, ${order.customer_name}.\n\nOrder: ${order.id}\n${order.items.map(i=>`${i.name} × ${i.quantity}`).join('\n')}\n\nTotal: USD ${(order.total/100).toFixed(2)}\nPayment: pay on delivery.\n\nThank you for shopping with LUMA.`);const host=c.region==='EU'?'api.eu.mailgun.net':'api.mailgun.net';try{const r=await fetch(`https://${host}/v3/${encodeURIComponent(c.domain)}/messages`,{method:'POST',headers:{Authorization:`Basic ${btoa('api:'+c.mailKey)}`},body:form});await db(`orders?id=eq.${order.id}`,'PATCH',{email_status:r.ok?'sent':'failed'});return r.ok}catch(error){console.error('Confirmation email failed',error instanceof Error?error.message:'unknown error');try{await db(`orders?id=eq.${order.id}&email_status=eq.sending`,'PATCH',{email_status:'failed'})}catch{}return false}}
