import {cookies} from 'next/headers';
import {env} from 'cloudflare:workers';
export function config(){const e=env as unknown as Record<string,string>;return {url:e.SUPABASE_URL||process.env.SUPABASE_URL,key:e.SUPABASE_SERVICE_ROLE_KEY||process.env.SUPABASE_SERVICE_ROLE_KEY,anon:e.SUPABASE_ANON_KEY||process.env.SUPABASE_ANON_KEY,origin:e.SITE_URL||process.env.SITE_URL,mailKey:e.MAILGUN_API_KEY||process.env.MAILGUN_API_KEY,domain:e.MAILGUN_DOMAIN||process.env.MAILGUN_DOMAIN,from:e.MAILGUN_FROM||process.env.MAILGUN_FROM,region:e.MAILGUN_REGION||process.env.MAILGUN_REGION}}
export function configured(){const c=config();return !!(c.url&&c.key&&c.anon&&c.origin)}
export async function db(path:string,method='GET',body?:unknown):Promise<any>{const c=config();if(!configured())throw Error('The shop is not open yet. Please check back soon.');const r=await fetch(`${c.url}/rest/v1/${path}`,{method,headers:{apikey:c.key!,Authorization:`Bearer ${c.key}`,'Content-Type':'application/json',Prefer:'return=representation'},body:body===undefined?undefined:JSON.stringify(body)});if(!r.ok){console.error('Database request failed',r.status);throw Error('We could not save your changes. Please try again.')}return r.status===204?null:r.json()}
export async function session(){const jar=await cookies();let id=jar.get('luma_cart')?.value;if(!id||!/^[0-9a-f-]{36}$/.test(id)){id=crypto.randomUUID();jar.set('luma_cart',id,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',path:'/',maxAge:60*60*24*30})}return id}
export async function identity():Promise<any>{const token=(await cookies()).get('luma_access')?.value;if(!token)return null;const c=config();const r=await fetch(`${c.url}/auth/v1/user`,{headers:{apikey:c.anon!,Authorization:`Bearer ${token}`}});return r.ok?r.json():null}
export function sameOrigin(req:Request){const origin=req.headers.get('origin');const expected=config().origin||new URL(req.url).origin;return origin===expected}
export function failure(e:unknown,status=503){return Response.json({error:e instanceof Error?e.message:'Something went wrong. Please try again.'},{status})}
export async function sendConfirmation(order:any){const c=config();if(!c.mailKey||!c.domain||!c.from)return false;const claim=await db(`orders?id=eq.${order.id}&email_status=eq.pending`,'PATCH',{email_status:'sending'});if(!claim?.length)return false;const form=new FormData();form.set('from',c.from);form.set('to',order.email);form.set('subject',`Your LUMA order ${order.id.slice(0,8).toUpperCase()}`);form.set('text',`Thank you for your order, ${order.customer_name}.\n\nOrder: ${order.id}\n${order.items.map((i:any)=>`${i.name} × ${i.quantity}`).join('\n')}\n\nTotal: USD ${(order.total/100).toFixed(2)}\nPayment: pay on delivery.\n\nThank you for shopping with LUMA.`);const host=c.region==='EU'?'api.eu.mailgun.net':'api.mailgun.net';try{const r=await fetch(`https://${host}/v3/${encodeURIComponent(c.domain)}/messages`,{method:'POST',headers:{Authorization:`Basic ${btoa('api:'+c.mailKey)}`},body:form});await db(`orders?id=eq.${order.id}`,'PATCH',{email_status:r.ok?'sent':'failed'});return r.ok}catch{return false}}
